server:
  port: 8083

spring:
  application:
    name: monster-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27019}
      database: monster_db

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://frontend-service:3000}

# Service auth pour validation token
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
